### PR TITLE
Fix day capitalisation typos

### PR DESCRIPTION
**Pull request by hugovk**
And remove a duplicate test line.

### CODE REVIEW

**Comment by jayfk** [comment]
First of all, thanks for this pull request!

I'm afraid I won't be able to merge it:

- It will break existing configurations
- The strings are for a config file. In my opinion, there's no need to capitalize correctly.

**Comment by hugovk** [comment]
How can we fix the day typos in the 1,000 PRs across GitHub? Or rather, in the new thousands of PRs that will be created :)

https://github.com/search?utf8=%E2%9C%93&q=%22Scheduled+daily+dependency+update+on%22&type=Issues

**Comment by jayfk** [comment]
The best way to would be to capitalize the day here: https://github.com/pyupio/pyup/blob/master/pyup/updates.py#L129-L130

**Comment by hugovk** [comment]
@jayfk Please see PR https://github.com/pyupio/pyup/pull/259.

**Pull request closed without merging**
